const products = [
  {
    id: 'inkter-bedroom-set',
    title: 'bedroom set',
    store: 'inkter',
    image: './img/image-1.jpeg',
    price: 149.95,
  },
  {
    id: 'minister-bookshelf',
    title: 'modern bookshelf',
    store: 'minister',
    image: './img/image-2.jpeg',
    price: 179.90,
  },
  {
    id: 'carmins-office-chair',
    title: 'office chair',
    store: 'carmins',
    image: './img/image-3.jpeg',
    price: 45.95,
  },
  {
    id: 'carmins-living-table',
    title: 'livingroom table',
    store: 'carmins',
    image: './img/image-4.jpeg',
    price: 75.95,
  },
  {
    id: 'carmins-bookshelf',
    title: 'old bookshelf',
    store: 'carmins',
    image: './img/image-5.jpeg',
    price: 55.90,
  },
  {
    id: 'stylish-sofa-set',
    title: 'large sofa set',
    store: 'stylish',
    image: './img/image-6.jpeg',
    price: 139.95,
  },
  {
    id: 'minister-sofa-set',
    title: 'sofa set',
    store: 'minister',
    image: './img/image-7.jpeg',
    price: 100.95,
  },
  {
    id: 'stylish-armchair-set',
    title: 'armchair set',
    store: 'stylish',
    image: './img/image-8.jpeg',
    price: 95.90,
  },
  {
    id: 'minister-dinning-table',
    title: 'dinning table',
    store: 'minister',
    image: './img/image-9.jpeg',
    price: 85.95,
  },
  {
    id: 'stylish-drawers-bedroom',
    title: 'drawers bedroom',
    store: 'stylish',
    image: './img/image-10.jpeg',
    price: 40.95,
  },
  {
    id: 'inkter-table',
    title: 'round table',
    store: 'inkter',
    image: './img/image-11.jpeg',
    price: 55.90,
  },
  {
    id: 'stylish-leather-sofa',
    title: 'leather sofa',
    store: 'stylish',
    image: './img/image-12.jpeg',
    price: 80.95,
  },
];